version: 2

jobs:
  # build ジョブ: CircleCI 上で Docker コンテナを作成してテストする
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Echo Test
          command: echo "CircleCI Test"
  # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
  deploy:
    machine:
      image: cimg/base:2021.04
    steps:
      - checkout
      # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys:
          fingerprints:
            # CircleCI上でSSHキー登録を行った際に作成されるfingerprintsを記入！！
            - 87:2f:53:7a:10:6b:89:f4:76:30:44:27:71:6f:4d:85
      # CircleCI に登録した環境変数を使って SSH
      - run:
          name: deploy
          command: ssh ${USER_NAME}@${HOST_NAME} 'git pull && docker-compose up'
      - run:
          name: docker-compose_up
          command: docker-compose up

workflows:
  version: 2
  # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
  build_and_deploy:
    # build ジョブと deploy ジョブを登録する
    jobs:
      - build
      - deploy:
          requires:
            # 依存性あるから deploy ジョブより先に build ジョブを実行してね、という命令
            - build
          # main ブランチに push された場合のみ deploy ジョブを実行する
          filters:
            branches:
              only: main