version: 2

jobs:
  # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys:
      # CircleCI に登録した環境変数を使って SSH
      - run:
          name: deploy
          command: ssh ${USER_NAME}@${HOST_NAME} 'git pull'

workflows:
  version: 2
  # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
  build_and_deploy:
    # build ジョブと deploy ジョブを登録する
    jobs:
      - deploy